language: c
before_script:
- git clone "https://github.com/ZIM555/android_prebuilts_gcc.git" "$HOME/android_prebuilt_toolchains"
- sudo apt-get install lzop
script:
- export ARCH=arm
- export CROSS_COMPILE="$HOME/android_prebuilt_toolchains/arm-eabi-4.7/bin/arm-eabi-"
- make -j4 arubaslim_defconfig
- make -j4 
- mv arch/arm/boot/zImage zImage
- md5sum zImage > md5
- mv zImage "zImage-$(date +%Y%m%d)-$(cat md5)"
- curl --upload-file "./zImage-$(date +%Y%m%d)-$(cat md5)" "https://transfer.sh/zImage-$(date +%Y%m%d)-$(cat md5)"
